#!/usr/bin/env python3
"""Generate Android and web adapters from the portable GHT theme catalog."""
import argparse
import json
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]


def luminance(color):
    rgb = [int(color[i:i + 2], 16) / 255 for i in (1, 3, 5)]
    linear = [c / 12.92 if c <= .04045 else ((c + .055) / 1.055) ** 2.4 for c in rgb]
    return sum(c * w for c, w in zip(linear, (.2126, .7152, .0722)))


def contrast(a, b):
    low, high = sorted((luminance(a), luminance(b)))
    return (high + .05) / (low + .05)


def render():
    data = json.loads((ROOT / 'themes/ght-themes.json').read_text())
    themes = data['themes']
    assert data['schemaVersion'] == 1
    assert len(themes) == 20
    assert len({t['id'] for t in themes}) == len(themes)
    assert len({t['label'] for t in themes}) == len(themes)
    assert {'default', 'dracula', 'solarized_dark', 'nord', 'gruvbox_dark'} <= {t['id'] for t in themes}
    kotlin = ['// Generated by scripts/generate-themes.py. Edit themes/ght-themes.json.',
              'package network.ght.pocketshell', '', 'internal object ThemeCatalog {',
              '    val all: List<TermTheme> = listOf(']
    css = ['/* Generated GHT theme tokens. Select with data-ght-theme="<id>". */']
    for t in themes:
        assert re.fullmatch(r'[a-z][a-z0-9_]*', t['id'])
        assert t['mode'] in ('dark', 'light')
        u, terminal = t['ui'], t['terminal']
        colors = list(u.values()) + [terminal[k] for k in ('background', 'foreground', 'cursor')] + terminal['ansi']
        assert len(terminal['ansi']) == 16
        assert all(re.fullmatch(r'#[0-9A-F]{6}', c) for c in colors), t['id']
        backgrounds = [terminal['background'], u['surface'], u['surfaceAlt'], u['control']]
        for role in ('text', 'muted', 'accent', 'error', 'success', 'warning', 'info'):
            for bg in backgrounds:
                assert contrast(u[role], bg) >= 4.5, (t['id'], role, bg, contrast(u[role], bg))
        assert contrast(u['onAccent'], u['accent']) >= 4.5, t['id']
        assert contrast(terminal['foreground'], terminal['background']) >= 4.5, t['id']
        q = lambda x: json.dumps(x, ensure_ascii=False)
        color = lambda c: '0x' + c[1:] + 'L'
        kotlin.extend([
            '        TermTheme(',
            f'            id = {q(t["id"])}, label = {q(t["label"])},',
            f'            description = {q(t["description"])}, dark = {str(t["mode"] == "dark").lower()},',
            '            tags = listOf(' + ', '.join(map(q, t['tags'])) + '),',
            '            ' + ', '.join(k + ' = ' + color(terminal[k]) for k in ('background', 'foreground', 'cursor')) + ',',
            '            ansi = listOf(' + ', '.join(map(color, terminal['ansi'])) + '),',
            '            ui = ThemeUiColors(',
            *['                ' + k + ' = ' + color(v) + ',' for k, v in u.items()],
            '            ),', '        ),',
        ])
        css.extend([f'[data-ght-theme="{t["id"]}"] {{', f'  color-scheme: {t["mode"]};',
                    f'  --ght-background: {terminal["background"]};'])
        for k, v in u.items():
            kebab = re.sub(r'[A-Z]', lambda m: '-' + m[0].lower(), k)
            css.append(f'  --ght-{kebab}: {v};')
        for k in ('background', 'foreground', 'cursor'):
            css.append(f'  --ght-terminal-{k}: {terminal[k]};')
        css.extend(f'  --ght-ansi-{i}: {v};' for i, v in enumerate(terminal['ansi']))
        css.append('}')
    kotlin.extend(['    )', '}'])
    return {
        ROOT / 'app/src/main/java/network/ght/pocketshell/ThemeCatalog.kt': '\n'.join(kotlin) + '\n',
        ROOT / 'themes/ght-themes.css': '\n'.join(css) + '\n',
    }


if __name__ == '__main__':
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--check', action='store_true', help='Validate contrast and require generated files to match')
    args = parser.parse_args()
    for path, text in render().items():
        if args.check:
            assert path.exists() and path.read_text() == text, f'Stale generated file: {path}'
        else:
            path.write_text(text)
    print('20 themes validated: unique IDs, complete ANSI palettes, readable UI text, matching Android/CSS adapters.')
